name: Main

on:
  push:
    branches:
      - 'main'

jobs:
  build_apk_aab:
    name: Build release artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with: { java-version: 17 }
      - name: Build release APK and AAB after test
        run: |
          ./gradlew testReleaseUnitTest assembleRelease bundleRelease
