name: Main

on:
  push:
    branches:
      - 'main'

jobs:
  build_apk_aab:
    name: Build debug artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with: { java-version: 17 }
      - name: Build and verify
        run: |
          ./gradlew testDebugUnitTest assembleDebug
      - name: Upload to Firebase
        run: |
          ./gradlew appDistributionUploadDebug
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
